kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa4mq-spring-app
  namespace: dev
spec:
  scaleTargetRef:
    kind: Deployment
    name: mq-spring-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
