apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: alfred4ibmOrg
  owner: alfred4ibmOrg
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/alfred4ibmOrg/multi-tenancy-gitops-apps.git
