apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCpnSqCdQ7+90nsHxwWsuDtsoZcWhgW49Rplyya1qszxCD5gzeIapXVO4me7vWmMppqY0nQGqyYET5WS5zZH6E2Fs4qsuA8nWzxYkT8fNY2TJHGO5BEvf6AvsilxcYZZ3XasKEl6i4uil4tkJCG0YlEFE2lxPbEXek4Ij4EtRrNgH6GFXvJkxC8oNJJSVQ+scSPoZ1jcAaSGnAgZEmQ9I66YH6xncswbLVD6DQKxdA3J4AmO4zQLz3jkBvdeb+gSiW1JoZswtrPatS78w2forLq7iB1DpHUUcHH9kCGi4co1jiv0Dp2lMJoIB41DlivNISKpDCVa7BHcJ7scJd9dqqLgsqPkRKZko1gbRZ1ZlEc0PsMWCgwwyn++2byQN5q+aOFyHx4yiJ71YpMwwRpjDrjsGOvC2QBZAweJhMWU6/IoXhDDk7Gy2yhoeWCxdUTqQzrHoAxJpHZRSO6r1GbmbPTgMOLDk8eZlWqsN1GwgoSaOfGipA1sK1AtGyR9cAZpDyykP2tqzW9oP9va4ypUjGga7fdm94u3IUba4bLwB+7fmTeLxez36JXp1w3C8bGXXSlKbw2luA4wgxvzAv2lKZadfkGCLwq++HJv4OkSql6fUIlVgD92pRfW4QbGJjMeaZ3WND3dKoaF28gcNSW9tgsYWzelI7UbMyOmpTpLmdW64ET0iMySgFWDZ77D7YueYDL/eFewPY4UA9SGW16JY9AHRoVYXLdMnEz9gO6HycgSlr2NTcWSMiMU1ztbx1pVYbmWIuTJf5AIBMSVdd6QY5XvjxijPt/IKYdpDRqQlxgb1uEUMCUOEj/qvSqumDPG0lZlJ9ppsSzEm7r2qY0AXFiIfeSnemzRP7ld8K7B8vpxs8XhVh5/vL1qwi1RFifwiPypJ/yIRvEPKU7lUAwsT4FQiX53x2tKzOy5jF2UeK4IPh0tZdnAtMZZb5MLQ6qfGY=
    IBM_ENTITLED_REGISTRY_USER: AgBzWc4MqcfliwfA7erLl5g8weqi7IF3Ff/Pr6l0vL3iS1Dsqw9DyXfmXxQFaLe97RNOn0UlhVEWV91vb9EAoK4O39LlqeSNftoJImMjVe6QYSoZTnlpmWkBFgZr/FXcVTBvKLuqCDC+voMngbMGtb5edfWDkNO5Ef9jWpArAu6H79DbCinRe2EftAq/o2IV8Z2ImuKEa6ltVfhEpY0BMsTDAeNoF0gbZ8oI2OXn2glziWIPw0kOO4KaqI1L1L0KcB4aIfTVdjnIz9/e6Sa7Cp/9ueWuk5lAtcQ0xsFja6eP7EJAp34tvxFaGDwNXG3beVINZt34oSHaYDZKVHU7bLESeFNGCCku1Ue0GRgaMUMYNaccGVCxo8GvgTpfl1twlJ+CsiyA9qu4EhoHnPl1l6Ob0m202JGiA8ZD8Q9SvyBayd4ePuG6XVASWgOYfhl/IFHq7OtgYoDdoMwij7J5hyE1PytnaLafAdpPLJnqr7mMB2hnqdKxlx3DGPxYWtqZ/PciMGFXwTbdGk7hjrLdB6nooMQBFlT2SaCSA3CuKhF8DgcFhhHdn51HLsrG/AdscKXUE87SboqxuzR80GlUaVjHVlx0/gAlB3rI9yMY8dLBnxLnzaE9eP5ERa1tFY36eFt96fqjQw3NZJ1U6daUnAze+rdNwtfiJbJjQ0JzYWJ4ImQi0uvEUOqmJwlq6zcPqiCftQ==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

