apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBQ0ZhBgjPepBnIJMxedKN7ykVzIwGdAQvzHoMO00mUx0WWF/g8Hb2HzOXdRESimc6yOYLNMarusD/tMldniQEsf7HEZ366EoroYovX+sT8FevhJXGunDPSW2NQZqH9HHEhqRATPK3GF2TTEmozZTZtxUNczcHQ+WK7pogA48wVhY0L4TKoWk89K41z8qtkYhBerQYtpF00reQ+1E3A/dBlVu5gwNz5dQl1hmn5Wb8yRyc6Ukigae7qMPAuD3/Y2W11/IveuLaHiCQ4PkOXqhkMjSCd47hnnvlNMwXEnqXqxIL8+DkSUzMwPgvyDJwJAx/GpvmvLHVMfVBx5c9vh06dZp3Mu7jiIm4hqZDXakFGi6Qn+ZzDKlgi/8zzpZxuTgDK2xp1KPAlQVORV0DAl0HwZOOjRvWX8j+uJ0t5gIAvHLhGapBtvium+XRoYUJddWiUcdjy3X5ZoNVaKvr1XTwzEsE5/OocjPhxQy8glhIOIlHePLi3vmtDsWYTncPD4e2Z+xWhZ/tR4V+bAkFv00UQ2F3oLxvnRJUEBWz6FgQ2iGZTc/dcKHEXSbsjQP7QpIf7IxRgQC3YzG0MYCcDTnqpgByostmtTchMKAt5BUm7Fis0pg9jr2G7qUcZrSxq603EFF1t33rYSOCldhPOiHiVbSv7qcvRYDrgi/6+mQF/M4aNZBxyr/0upyg+AFdSJ0LTAZV1IRMYqKI53A9MVSpn77iZMZlZQPDZHFEHKqyHZ5ePL7T2yzp/LgD6Pfk+kt5r59TD7q8HNBrfS4ZEeB6kmnBYqc6dhDN2F9USka+yKajtPdTR/vekRDn/T42z1SQOa6iKJ6DaT19skiSu0hf3Kk4qM1nLJED+KxNBDg2N1bxYHxICWAyarkK1BeR2XEdKaUgxfqZeZULii1a3HYJM+Gf6ECieEUOJoh7r5DsUWSO9XOY+j7KVfaL6+v65+HA=
    IBM_ENTITLED_REGISTRY_USER: AgCKSEwjVx1hExAWnSVdWeYIqbUWaKbvJi+JWrH79Es0BivgVPSWPwKRuysbjb+z1PWNRJlp2z1NfSHBTjWyZ8LNFfPeyTznN7dq84KQm2yDxuLATtPFfQO5F30jceZh9T6nSmPHRbBPrXM1oaYGM40giONJb2U4VBnsCZAI7ytbh/FTLNx0TLHgWWap30td8z92Rbi8cFNuLm+XvxWuacOBaJQ4SFmKibRL9KmZ5tunyRmLqDg/0eo9HEKUpO6qZWKdpYa7Hfw5DcAv9npL2WKokv6EIosimeflXjl2NM49StsxUU+3M9BxnGArb8Da8Uszc62ieM2+kxTG6S2HkhxH9tkZgJsyIRPX+YL9+gxIJWJg4LiLFdCnLVGoZg13aoUvyGzu52ShZpJKWVNBwImS4pDoSX/FFNVyRbpQvPK9/U7KYVLC9WboGv162vAQSd/nN0F0jV15w2cQJPWf+whTYhK+YJbPGvhGzf9fCPIBonPyw5Gs51ouJBhqSWCLQJY1/R4ga4uezw4GbwAGA/HxlCQTUz+TC4MabnDRsyMSZ+j6A3P2BdelJ0hYv0fKYdj2tk9fYwu0HhWJsi0+Otjqwh15FAI6Z7T1aa+2KUF/U4JppcprZqjquli5mSyFabfFDcOgY6xaMwQ9lWrP9xOR7x/MFb58/VskrGP8ErOB0Zmf/zOhrmN5iziyyNh03VMkgQ==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

