apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCPIUaB8u5I1gbxEkwnumbE9QO+7pRIwST4Sv/0Ou8SopwBDWqAILWi0L2gu5jQF3yAcGv+hsuVrAnbqWJo1sgGn9EqSEYpA8iY+PtUgSRN/RLDQvjtKfIFYRYhNkIfa1Sc8vgO6UH4xUjCKWHyxdA43uVsp5ZLB4/dzORbnH9GxTZzSm7lbluiRSiZfBzAEeVM2WS+imSLs+iqrdv4rvxKFJ7hnVyPjvZShDkWS7tOD3ZQnU0B2zOI3Qtpi1p6sq9hn/RfWqAFh+M2R74YD2+gJfs0JTYOZ7NTfLaY5hY1LRYpf3JO0a4G6Zn51nPobdPGowmqWTcD46Nrl3hAU/DWDsWNaUdP823cv9JFxRzM2RiyaIg48kvIuKEBcVzjfMso3nf892mgkoWarkvOft+pxVoaD+S3XQLeAQf/2ZW1hPV7PPYyAspU4ZPaXOayltY7a7yQnX445MrA29RTpV7XAiwTjfF+b6Z+8Fql4XlXWeIYd8xKrtrDXW/nKgbDh1+3mxGlI2EhuMc0H0OCWUHVNGi08MYkrdh74xV9VQRi+nZq+LFZggNWtjyUZeZC56mozdvwi8jR5WxyR2l+QcUbPFjqLQwtTFsVv+5tUM6HzBTpx+Umo1ScmNHf5eflCtsoQDxcjzKxr5HBJfoCsQy2kct8RV+0rp2raOldgEBohzOq3NBmtw/KMSN6KiAKHzWzeaw6isyMp7fupOD3m5YkinN5xYm/a5KFE6uHQvuQBns0i7WA3lge/CEQow7XRlwNdQ0itufegeyYzLupOJoi7xxtC3zZ2YSxUJc8dxV91Gou0WpYGvpFjZtY1j5Dz1rdFRL99wvt0YDXADFeCa86k7gOOulDhDkWFjCTWg7k7jx8UBMSOr1jvPLh2qX0ViHtniiPOvPcR4Mk/uAk3qH9t34/XmgCgsP37IW6aBBFbDhAx1DEq/8D5qqJ1/ctfEU=
    IBM_ENTITLED_REGISTRY_USER: AgBaBqZyAR7kgaMFs1bSDStPnVlns+ytZ6JRJWhKe8GXa8xnrEw8ZfcO0IHW743sasDBxysWAEy+NAtGEFra3BGU6EK8lQdua6vR+xBVUdMWGIzSKeYr9Ptf5qX5CFIZRdrMt+EOsm8LQgS/0c8rEzJBdRCHjexj9zqYJ7guuRc4p13yT7YQcXNyGNR3dPHRKwdcImF8XkzSYz0vxfEj2wxhyWKL4gHvDJ9VUNHKqEGiyj4sDYNjU2EyILNUZa69T6g5qdghEaxPFUmG4+CMyyPK8XFBYAtVMjkeJlDH6EFWwjFMv+jlyNRaHQoAhHRQ7XNB2P4qthFK3WrDUMi/YNsaaakFHp1WOOZpImKVzBKqNGJQxJDMAtE2J7xK1YFSNnMoF50hBSru8HBVxV6/+LFEdn4scTMDyESh+gkWyxFgMHgY+4q7C6eG9fn0sDL6YFEfDJauEE+yJ4sJq8gib4phRfbxjAaqP7t5VyfzKKGNK1pgz/VAKomuaQXg/h4FDNTPh4rcB8VPjQWUs6u6DKKMdbY5lXAOOBZXO14j5LrCJpzT2MBC0Kw54UsNr/t1kVSOEU0S6iL5OB4cDA3IxJzSVRWzCdnGlQWIm2ev1Yc8dub0FhO1MyJ/nL3YevNNWieeJN3dn4vwbZiMj8jjhb3aVL7vHtkgZnulX+HcJfg1Kofo8AKwCSLPnnJh/dV+XEe3Pw==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

