apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgC/T84pggyP8IaG6OiYrYgXW9Ok90Z5rdC6pkD84J60OEXxaJHkcH4KvQSvJoCnI9ZL0m9ZLC28EBFTZA15vE1OVSXWPtjzd6eLMEbReYG9zwvWn+1tJU3VHrEGfamB3lbKCbZuVviZXNtHRbv6m6miYM3OyYn6JHxEjrbqEkJECvKeENENnsf+ZCWcXlKLCu42dBkXmpQtXVVzLauGsweRtqVk/5F1B3srGzOY75PyToVzZPcJYKRXDNDiTEzvYZX/3HDzxRnHahPa1irVaqDfMLJBy94MXtUWBuVV3P7JArB+bfHa9Rft+p9M2oKt4hblKcnFb8O2iWH9r2oiOBw5sCuBwTYZrsz7UJF0usSlXqce1QX5MQJ9e6eqfAJWC2mwH3o2kQdhJoxwvBoiijzCsOqZCe/Ucf5FOesTP65WtPaDamchUhII97RHFdBOBbMKr1QGe8MReKmnN6d32gKtQgXUU3wq3LYBX3eMmS84VEFmT/axoWprFJjStMgwWdNlGd/tWI6f4PgxxtXKx0xo7ViyFPPwylZG6kOW0eiOhM9JdznDReRQL5Ei6b2TMpa05K8oQ0h+39wAaGz+mzcZZ2naykh8hvvTaoY+7tF7IoOaYFSBZSR9toPunEN1CQXWSChd46UeNdGW5gy1ORJUNa2+OQzU7/GMmm8R1lV11AtXAt/+JRbnlyN9kouO/hE0jfeg58+7KiRNve8eQQbW5+R11Ol1iECX7Q4EcJx8JZ4yQeYuev/NH15HvQzG4xU/3ERGs18SK/CBQrjqR+nuKOEB+dgvShk5vBamDXQ9q3masVrvktI96AxnuXsZlR6eqetnsa/zAl9en7Mi/zu04bI9WjJ7ls3idqdSVX5dhBeVjkRhRx5OkNlvSMhdSUtCewEzbUZaqEJCxHLpNHUXKvHs438BkAHeEHnRyV4DX03dvMS8YwpyXek7PvrA7Oo=
    IBM_ENTITLED_REGISTRY_USER: AgCnmwL8tzFLQ9mEz5clhZ41dNSUP8N1DSXaW19Gh4G2RyIVctKtL+DPXkA4w5EXC7sErVhkI1H+Zx6YfP1VM0Fpqs4KMEEp5wUK9vTOEtGfxuD20DV5K6DiX8XOKj8MNH3JBKfwcUr13AyopyYxanj9bU7f25Z9GkgNNEVh5gTfO3uP9Ejgs0wsj0K7SDvmMyeX4b5xbQiolICCmX7EzKhi8KxVAnZnr91sHvVG+QvsONw5gZULSFTocpbaFYnTzpL79qxMc67au3io6HpXdQVohV8LUrq0SKHceNVRqs2lFfJ0FlJZUdvRpZXK4yOL94ODBe0+AZOJhMKqR13oxf1p7nNPI2Smvvyf3jz5tmGzLjE25dw+hKrNPE2IGYCG6ifmL1FHMtnktbZahxo2nHt3SReI8MZcTTNgpfrLiy0aX4TBKovAm7aT2q+e7WldTu9eQ/GYedBUBuaxe9+iIV8LWmXpUwLBEmWjxUhWQskoRT0IDkVyjirtUeoPzy2kw4IxcgpslJ0at3NRX+6obVh5YIkYUyF4v+e5n6ghcBFLMu+TbboO1OVewKkLis7PiuvG/VQef3Csf/uHLELWAmnEOSD24t1GwCb9FI/1wIRlsGqYYvou0jXedTB4IzjpNQcHlfK01yxwgldqhIrf7qSz4DYnbAGMhOU3hzq4ews9uxYux4X2av0xb6J1r2w78dOI8w==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

