apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCndGvwuFf/inEnJlu635HNLNvP2o+dWYR0XTSUPN8AH4NksSip7ir8zLKm1mIc8+jdCcx+j4uCsqJ5qLpvCHwqZYE0giKWfbu1kyZUw+rpT4ZWjV5QInbeejcsOR2efg0td81Y1ceRPUb7+UlwMBdjqHkqdliw36R29qn6HuqMaChIhjTfchhP2lVm4AE7KFMWcz23LQJaiLa5oOpHWhMbelx5lvPNO6c9mpix5yoljkPrtqyHq2Z0v/jxdnvvIxfxDG9aY00/HI7gNcGa9FCcIcrDseWzP9+aVzO9mI6uIPxoc+I7AoDnNVLHdYQz0QxfX4bg2Tea2dc3odY9bd871opucXV2miyCw9qH2rdjK8cm/5Dvnd0hcrdhqMsmZ6FJaK/CsKtZ8ErzCCqbPpwcDO6pYnLcWpeJ8huzLEJCKiapQA85DAhtCRLpsJH2wCR7xkFSYosWnRFF3bYTOHP5mHXpp6QC90IwIpHUTz2tf8aqo3X/nTmkKM6KREqajuEqs9vOUKowq1WqtXfpAU5ijwZf1OqV/uk+hiE6ncO0drIR3vnCNcUdro46v/nZeDYeXgn+kTDbaJ5LNMuPyk5wzFkrQ1HtqU/FLrJDL/zSq59CMbPA64ORG6WN8O1WLY/n+jos04FPTJJFHGKao92IPTp4GAQ3z8agFE8aM9hIdT2gmjoFnnDkC+QZxW/zPKQu1qxeE2TXdNpi4P0dgwvuw3rqksJiM33zXZ2ePsIWY0wwzZ1PH+bL8r5SrQKfY9+2rfb+nIsWsnvmk8DBNRyI+VsV0rDJ3hGrAlYSBXl0+0rWanntA3aKRwxK5/H3CyLDbWOBVG8/McBjcqd0c6rHApFJC7PVdl4OeI8vKruKpCAeWULUkw6N4vHIj6mEDCmaVAxMxbmF40FyUz6A2YcqJprYQtE/FXxt66S7+D/oeIuMsIiytwWzfbMjRx+w1S8=
    IBM_ENTITLED_REGISTRY_USER: AgBTI5wUI+m71AuMvpnlD3ZojzZGHCHf/Vt+mYqDekhvK9t6gZhhN0uZ4N4d+++hb2J++4vrL5yIcyU8Tguel8mDFUp+XyNYBnzzYK50i5+FgiBlyDzilaeAo37b35bLLJuUvx69bOsEmAhMuHc2hUzWWX0jfSTeVB8cBXKf11CScLeV6QC2I7emJ5cx8ZecJTFwh8q8KfgDKuHzkErFeUQBDbJsaBcd5XGTdUfckivD5vs0QXc9tJKB9JtPPE3miPihuFc1FqgiYhasUCBkvf5H1YepBypU3tpHbANOC/4B1nl24tyvcoUp+ki4w5E07h2fyUIiP0PUuz9ySL+NTkHxpkTozutV67Lkom2WxUU+HhUQyxyT8zfhS+SrJDO83hCSF2Bbp6EgLtuXUrUCMLeihwFhkJnhtGqFVn93YCJbqhPVzAYliyLhtqnfpYt00ZaTTqZDnO4Hdgt1hU8Ur9gcrqSfiHqVeAqDaAlCCqMI2VxoRtYB57PzxbowMqwQc/vaFJntgAjVrt8WHA3d0FRHl6i8hBveHaZijlmrrSjFfr0NYLz1Y8rG+BOpC2FMd7iB/GNmmXE6F8H7we6cJS/qMGk/dAVrOvNWVJtPY53AnJZL7A0giGEZp78UsN7rgi78hsUKGRFjKhcbKQF7stBifdqKhTJQaQMBgwNIJdsMRF8dSdhjUteOe6NIxIzwVQbn9A==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

